первая страница.
htmlacademy-htmlcss/2153301-device-35 pull request #2
Opened 2022-09-26 11:01 UTC by EugeneShlyk

2022-09-26 23:45 UTC, Espanol-nikkol requested changes

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +      <form class="search" action="#" method="post">
для action есть значение в описании задания

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +      <img src="#" alt="логотип девайс">
Таки это должно быть ссылкой

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +            <a class="navigation-link" href="" >
пустые ссылки оставлять не надо, вставь в них #
Когда оставляешь её пустой, браузер не признаёт её ссылкой

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +        <h2>Наименование товара</h2>
А кто такой "наименование товара"? Не вижу в макете
Может "Каталог товаров" тут должен быть?

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +        <div></div>
пустой див?

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +      <section class="slider">
https://www.figma.com/file/B2S5PupxHYVFbrWD9CWZgp/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=11549%3A3957

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +      <section class="services">
https://www.figma.com/file/B2S5PupxHYVFbrWD9CWZgp/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=346%3A294

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +        <div></div>
и снова пустой фантомный див)

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +        <div></div>
опять он)

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +        <div></div>
начинаю подозревать за ними какой-то смысл

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +        <div></div>
![image](https://user-images.githubusercontent.com/42237828/192399745-c3d126d0-913a-4cd6-9713-7965b0346a18.png)

если див для этого, то такая штука чисто декоративная и делается стилями

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +            <img src="" alt="you-tube">
без дефиса

2022-09-26 23:45 UTC, Espanol-nikkol commented on index.html
> +      <img src="" alt="html-academy">
на академию - ссылка

2022-10-02 11:18 UTC, Espanol-nikkol requested changes

2022-10-02 11:18 UTC, Espanol-nikkol commented on index.html
> +      <a><img src="images/device-logo.svg" width="145" height="36" alt="логотип девайс"></a>
Ссылка на главную страницу)
Чтобы ссылка была ссылкой, ей нужен href, иначе браузер её автоматически воспринимает текстом

2022-10-02 11:18 UTC, Espanol-nikkol commented on index.html
> +        <ul class="services-list">
тут скорее два списка
список заголовков (левая часть) и список описаний (правая часть)
работать такое может только с помощью JS, но и сверстать нормально получится, только если это будет отдельные два списка

2022-10-02 11:18 UTC, Espanol-nikkol commented on catalog.html
> +                <label class="control">
каждый label должен иметь for="id-input"

2022-10-02 11:18 UTC, Espanol-nikkol commented on catalog.html
> +                <input type="checkbox" class="control-input" name="Черный" checked>
инпут либо обернут в label, либо имеет id для связывания с label
name должно быть на английском

2022-10-02 11:18 UTC, Espanol-nikkol commented on catalog.html
> +            <a href="#" class="product-card-link">
https://www.figma.com/file/B2S5PupxHYVFbrWD9CWZgp/HTML-1-%2F-%D0%94%D0%B5%D0%B2%D0%B0%D0%B9%D1%81?node-id=11558%3A5747

У каждой карточки есть ссылка кнопка при наведении и может быть надпись new

2022-10-02 11:18 UTC, Espanol-nikkol commented on catalog.html
> +          <a class="pagination-link" href="#">...</a>
не ссылка, ей вести некуда

2022-10-02 11:19 UTC, merged

2022-10-02 20:57 UTC, EugeneShlyk commented on catalog.html
> +                <input type="checkbox" class="control-input" name="Черный" checked>
там влажен инпут в лэйбл, наверно я ввел в заблуждение не отступив дополнительно два знака у инпута что-бы визуально было понятнее.

2022-10-02 21:25 UTC, EugeneShlyk commented on index.html
> +      <a><img src="images/device-logo.svg" width="145" height="36" alt="логотип девайс"></a>
Но мы и так находимся на главной странице. Надо вообще тег <a> убирать или тегу пустой href добавлять или решетку в href вставлять?